### ISSUE TITLE
When I build this project shows errors

### ISSUE THREAD

**Issue by Lohita9** [developer-krushna/Dex-Editor-Android#2]
```
> Task :app:compileDebugJavaWithJavac
2024-07-04T11:37:15.6697882Z /home/Dex-Editor/app/src/main/java/modder/hub/dexeditor/fragment/SmaliMethodListFragment.java:297: error: constant expression required
2024-07-04T11:37:15.6700541Z                             case R.id.close:
2024-07-04T11:37:15.6870788Z                                      ^
2024-07-04T11:37:18.4698973Z /home/Dex-Editor/app/src/main/java/com/android/tools/smali/util/jcommander/HelpFormatter.java:174: error: incompatible types: MainParameter cannot be converted to ParameterDescription
2024-07-04T11:37:18.4702221Z                         ExtendedCommands.parameterArgumentNames(leafJc.getMainParameter());
2024-07-04T11:37:18.4704214Z                                                                                        ^
2024-07-04T11:37:18.4707541Z /home/Dex-Editor/app/src/main/java/com/android/tools/smali/util/jcommander/HelpFormatter.java:254: error: incompatible types: MainParameter cannot be converted to ParameterDescription
2024-07-04T11:37:18.4710577Z                             ExtendedCommands.parameterArgumentNames(leafJc.getMainParameter());
2024-07-04T11:37:18.4712097Z                                                                                            ^
2024-07-04T11:37:18.4714347Z /home/Dex-Editor/app/src/main/java/com/android/tools/smali/util/jcommander/HelpFormatter.java:307: error: cannot find symbol
2024-07-04T11:37:18.4842052Z                         String commandDesc = leafJc.getCommandDescription(commandName);
2024-07-04T11:37:18.4843118Z                                                    ^
2024-07-04T11:37:18.4843991Z   symbol:   method getCommandDescription(String)
2024-07-04T11:37:18.4845031Z   location: variable leafJc of type JCommander
2024-07-04T11:37:18.7696696Z Note: Some input files use or override a deprecated API.
2024-07-04T11:37:18.7698688Z Note: Recompile with -Xlint:deprecation for details.
2024-07-04T11:37:18.7699274Z 
2024-07-04T11:37:18.7699679Z > Task :app:compileDebugJavaWithJavac FAILED
2024-07-04T11:37:18.7700810Z Note: Some input files use unchecked or unsafe operations.
```

**Comment by developer-krushna** [comment]
> Any update

Oh sorry for the late response...I see the error it seems to be a build tool error..I am still using Skechware pro java 11 version but there is no issues like this which you got

**Comment by developer-krushna** [comment]
> I am using AndroidIDE to build this project.

Try using Android Studio if you have..but I don't know this type of issues

**Comment by developer-krushna** [comment]
> I also tried using Android Studio, but the same issue arises.

I have seen one guy already builded up .. You are the first who have this type of issues and also I don't know how to fix this  .Sad

**Comment by developer-krushna** [comment]
> Could you please provide me with the .swb backup file for Sketchware Pro so that I can build it in the Sketchware Pro app?

Just copy all java files to java folder.. and Call the MainActivity from actual main activity of Skechware project

**Comment by developer-krushna** [comment]
> > > I also tried using Android Studio, but the same issue arises.
> > 
> > 
> > I have seen one guy already builded up .. You are the first who have this type of issues and also I don't know how to fix this  .Sad
> 
> Here is the Deprecated warning
> 
> ```
> > Task :app:compileDebugJavaWithJavac
> /home/Dex-Editor/Dex-Editor/app/src/main/java/modder/hub/dexeditor/fragment/SmaliMethodListFragment.java:96: warning: [deprecation] ProgressDialog in android.app has been deprecated
>   private ProgressDialog coreprog;
>           ^
> /home/Dex-Editor/Dex-Editor/app/src/main/java/modder/hub/dexeditor/fragment/SmaliMethodListFragment.java:97: warning: [deprecation] ProgressDialog in android.app has been deprecated
>   private ProgressDialog coreprog2;
>           ^
> /home/Dex-Editor/Dex-Editor/app/src/main/java/modder/hub/dexeditor/fragment/SmaliMethodListFragment.java:214: warning: [deprecation] AsyncTask in android.os has been deprecated
>             new AsyncTask<Void, Void, List<HashMap<String, Object>>>() {
>                 ^
> /home/Dex-Editor/Dex-Editor/app/src/main/java/modder/hub/dexeditor/fragment/SmaliMethodListFragment.java:214: warning: [deprecation] AsyncTask() in AsyncTask has been deprecated
>             new AsyncTask<Void, Void, List<HashMap<String, Object>>>() {
>             ^
> /home/Dex-Editor/Dex-Editor/app/src/main/java/modder/hub/dexeditor/fragment/SmaliMethodListFragment.java:216: warning: [deprecation] doInBackground(Params...) in AsyncTask has been deprecated
>               protected List<HashMap<String, Object>> doInBackground(Void... voids) {
>                                                       ^
>   where Params,Result are type-variables:
>     Params extends Object declared in class AsyncTask
>     Result extends Object declared in class AsyncTask
> /home/Dex-Editor/Dex-Editor/app/src/main/java/modder/hub/dexeditor/fragment/SmaliMethodListFragment.java:214: warning: [deprecation] AsyncTask() in AsyncTask has been deprecated
>             new AsyncTask<Void, Void, List<HashMap<String, Object>>>() {
>                                                                        ^
> /home/Dex-Editor/Dex-Editor/app/src/main/java/modder/hub/dexeditor/fragment/SmaliMethodListFragment.java:247: warning: [deprecation] onPostExecute(Result) in AsyncTask has been deprecated
>               protected void onPostExecute(List<HashMap<String, Object>> result) {
>                              ^
>   where Result is a type-variable:
>     Result extends Object declared in class AsyncTask
> /home/Dex-Editor/Dex-Editor/app/src/main/java/modder/hub/dexeditor/fragment/SmaliMethodListFragment.java:269: warning: [deprecation] execute(Params...) in AsyncTask has been deprecated
>             }.execute();
>              ^
>   where Params,Progress,Result are type-variables:
>     Params extends Object declared in class AsyncTask
>     Progress extends Object declared in class AsyncTask
>     Result extends Object declared in class AsyncTask
> /home/Dex-Editor/Dex-Editor/app/src/main/java/modder/hub/dexeditor/fragment/SmaliMethodListFragment.java:280: error: constant expression required
>               case R.id.close:
>                        ^
> /home/Dex-Editor/Dex-Editor/app/src/main/java/modder/hub/dexeditor/fragment/SmaliMethodListFragment.java:406: warning: [deprecation] AsyncTask in android.os has been deprecated
>             new AsyncTask<Void, Void, String>() {
>                 ^
> /home/Dex-Editor/Dex-Editor/app/src/main/java/modder/hub/dexeditor/fragment/SmaliMethodListFragment.java:406: warning: [deprecation] AsyncTask() in AsyncTask has been deprecated
>             new AsyncTask<Void, Void, String>() {
>             ^
> /home/Dex-Editor/Dex-Editor/app/src/main/java/modder/hub/dexeditor/fragment/SmaliMethodListFragment.java:408: warning: [deprecation] doInBackground(Params...) in AsyncTask has been deprecated
>               protected String doInBackground(Void... voids) {
>                                ^
>   where Params,Result are type-variables:
>     Params extends Object declared in class AsyncTask
>     Result extends Object declared in class AsyncTask
> /home/Dex-Editor/Dex-Editor/app/src/main/java/modder/hub/dexeditor/fragment/SmaliMethodListFragment.java:406: warning: [deprecation] AsyncTask() in AsyncTask has been deprecated
>             new AsyncTask<Void, Void, String>() {
>                                                 ^
> /home/Dex-Editor/Dex-Editor/app/src/main/java/modder/hub/dexeditor/fragment/SmaliMethodListFragment.java:430: warning: [deprecation] onPostExecute(Result) in AsyncTask has been deprecated
>               protected void onPostExecute(String extractedCode) {
>                              ^
>   where Result is a type-variable:
>     Result extends Object declared in class AsyncTask
> /home/Dex-Editor/Dex-Editor/app/src/main/java/modder/hub/dexeditor/fragment/SmaliMethodListFragment.java:460: warning: [deprecation] execute(Params...) in AsyncTask has been deprecated
>             }.execute();
>              ^
>   where Params,Progress,Result are type-variables:
>     Params extends Object declared in class AsyncTask
>     Progress extends Object declared in class AsyncTask
>     Result extends Object declared in class AsyncTask
> /home/Dex-Editor/Dex-Editor/app/src/main/java/modder/hub/dexeditor/fragment/SmaliMethodListFragment.java:469: warning: [deprecation] ProgressDialog in android.app has been deprecated
>         coreprog = new ProgressDialog(getActivity());
>                        ^
> /home/Dex-Editor/Dex-Editor/app/src/main/java/modder/hub/dexeditor/fragment/SmaliMethodListFragment.java:469: warning: [deprecation] ProgressDialog(Context) in ProgressDialog has been deprecated
>         coreprog = new ProgressDialog(getActivity());
>                    ^
> /home/Dex-Editor/Dex-Editor/app/src/main/java/modder/hub/dexeditor/fragment/SmaliMethodListFragment.java:478: warning: [deprecation] setMessage(CharSequence) in ProgressDialog has been deprecated
>       coreprog.setMessage(null);
>               ^
> /home/Dex-Editor/Dex-Editor/app/src/main/java/modder/hub/dexeditor/fragment/SmaliMethodListFragment.java:522: warning: [deprecation] ProgressDialog in android.app has been deprecated
>         coreprog2 = new ProgressDialog(getActivity());
>                         ^
> /home/Dex-Editor/Dex-Editor/app/src/main/java/modder/hub/dexeditor/fragment/SmaliMethodListFragment.java:522: warning: [deprecation] ProgressDialog(Context) in ProgressDialog has been deprecated
>         coreprog2 = new ProgressDialog(getActivity());
>                     ^
> /home/Dex-Editor/Dex-Editor/app/src/main/java/modder/hub/dexeditor/fragment/SmaliMethodListFragment.java:530: warning: [deprecation] setMessage(CharSequence) in ProgressDialog has been deprecated
>       coreprog2.setMessage(null);
>                ^
> /home/Dex-Editor/Dex-Editor/app/src/main/java/modder/hub/dexeditor/SketchwareUtil.java:68: warning: [deprecation] getView() in Toast has been deprecated
>     View _view = _toast.getView();
>                        ^
> /home/Dex-Editor/Dex-Editor/app/src/main/java/modder/hub/dexeditor/SketchwareUtil.java:77: warning: [deprecation] setBackgroundDrawable(Drawable) in View has been deprecated
>     _view.setBackgroundDrawable(_gradientDrawable);
>          ^
> /home/Dex-Editor/Dex-Editor/app/src/main/java/modder/hub/dexeditor/SketchwareUtil.java:107: warning: [deprecation] getView() in Toast has been deprecated
>     View _view = _toast.getView();
>                        ^
> /home/Dex-Editor/Dex-Editor/app/src/main/java/modder/hub/dexeditor/SketchwareUtil.java:118: warning: [deprecation] setBackgroundDrawable(Drawable) in View has been deprecated
>     _view.setBackgroundDrawable(_gradientDrawable);
>          ^
> /home/Dex-Editor/Dex-Editor/app/src/main/java/modder/hub/dexeditor/SketchwareUtil.java:191: warning: [deprecation] NetworkInfo in android.net has been deprecated
>     NetworkInfo _activeNetworkInfo = _connectivityManager.getActiveNetworkInfo();
>     ^
> /home/Dex-Editor/Dex-Editor/app/src/main/java/modder/hub/dexeditor/SketchwareUtil.java:191: warning: [deprecation] getActiveNetworkInfo() in ConnectivityManager has been deprecated
>     NetworkInfo _activeNetworkInfo = _connectivityManager.getActiveNetworkInfo();
>                                                          ^
> /home/Dex-Editor/Dex-Editor/app/src/main/java/modder/hub/dexeditor/SketchwareUtil.java:192: warning: [deprecation] isConnected() in NetworkInfo has been deprecated
>     return _activeNetworkInfo != null && _activeNetworkInfo.isConnected();
>                                                            ^
> /home/Dex-Editor/Dex-Editor/app/src/main/java/modder/hub/dexeditor/SketchwareUtil.java:214: warning: [deprecation] toggleSoftInput(int,int) in InputMethodManager has been deprecated
>     _inputMethodManager.toggleSoftInput(InputMethodManager.HIDE_IMPLICIT_ONLY, 0);
>                        ^
> /home/Dex-Editor/Dex-Editor/app/src/main/java/modder/hub/dexeditor/SketchwareUtil.java:220: warning: [deprecation] SHOW_FORCED in InputMethodManager has been deprecated
>     _inputMethodManager.toggleSoftInput(InputMethodManager.SHOW_FORCED, 0);
>                                                           ^
> /home/Dex-Editor/Dex-Editor/app/src/main/java/modder/hub/dexeditor/SketchwareUtil.java:220: warning: [deprecation] toggleSoftInput(int,int) in InputMethodManager has been deprecated
>     _inputMethodManager.toggleSoftInput(InputMethodManager.SHOW_FORCED, 0);
>                        ^
> /home/Dex-Editor/Dex-Editor/app/src/main/java/modder/hub/dexeditor/TextEditorActivity.java:111: warning: [deprecation] ProgressDialog in android.app has been deprecated
>   private ProgressDialog coreprog;
>           ^
> /home/Dex-Editor/Dex-Editor/app/src/main/java/modder/hub/dexeditor/TextEditorActivity.java:180: warning: [deprecation] onBackPressed() in ComponentActivity has been deprecated
>   public void onBackPressed() {
>               ^
> /home/Dex-Editor/Dex-Editor/app/src/main/java/modder/hub/dexeditor/TextEditorActivity.java:290: warning: [deprecation] Handler() in Handler has been deprecated
>           new Handler() {
>           ^
> /home/Dex-Editor/Dex-Editor/app/src/main/java/modder/hub/dexeditor/TextEditorActivity.java:290: warning: [deprecation] Handler() in Handler has been deprecated
>           new Handler() {
>                         ^
> /home/Dex-Editor/Dex-Editor/app/src/main/java/modder/hub/dexeditor/TextEditorActivity.java:343: warning: [deprecation] create(IThemeSource) in TextMateColorScheme has been deprecated
>       return TextMateColorScheme.create(themeSource);
>                                 ^
> /home/Dex-Editor/Dex-Editor/app/src/main/java/modder/hub/dexeditor/TextEditorActivity.java:358: warning: [deprecation] getThemeSource() in TextMateColorScheme has been deprecated
>           getColorScheme(themeName).getThemeSource());
>                                    ^
> /home/Dex-Editor/Dex-Editor/app/src/main/java/modder/hub/dexeditor/TextEditorActivity.java:352: warning: [deprecation] create(IGrammarSource,Reader,IThemeSource) in TextMateLanguage has been deprecated
>       return TextMateLanguage.create(
>                              ^
> /home/Dex-Editor/Dex-Editor/app/src/main/java/modder/hub/dexeditor/TextEditorActivity.java:372: warning: [deprecation] ProgressDialog in android.app has been deprecated
>         coreprog = new ProgressDialog(this);
>                        ^
> /home/Dex-Editor/Dex-Editor/app/src/main/java/modder/hub/dexeditor/TextEditorActivity.java:372: warning: [deprecation] ProgressDialog(Context) in ProgressDialog has been deprecated
>         coreprog = new ProgressDialog(this);
>                    ^
> /home/Dex-Editor/Dex-Editor/app/src/main/java/modder/hub/dexeditor/TextEditorActivity.java:380: warning: [deprecation] setMessage(CharSequence) in ProgressDialog has been deprecated
>       coreprog.setMessage(null);
>               ^
> /home/Dex-Editor/Dex-Editor/app/src/main/java/modder/hub/dexeditor/JavaViewActivity.java:144: warning: [deprecation] Handler() in Handler has been deprecated
>         new Handler() {
>         ^
> /home/Dex-Editor/Dex-Editor/app/src/main/java/modder/hub/dexeditor/JavaViewActivity.java:144: warning: [deprecation] Handler() in Handler has been deprecated
>         new Handler() {
>                       ^
> /home/Dex-Editor/Dex-Editor/app/src/main/java/modder/hub/dexeditor/JavaViewActivity.java:197: warning: [deprecation] onBackPressed() in ComponentActivity has been deprecated
>   public void onBackPressed() {
>               ^
> /home/Dex-Editor/Dex-Editor/app/src/main/java/modder/hub/dexeditor/DexEditorActivity.java:119: warning: [deprecation] ProgressDialog in android.app has been deprecated
>   private ProgressDialog prog;
>           ^
> /home/Dex-Editor/Dex-Editor/app/src/main/java/modder/hub/dexeditor/DexEditorActivity.java:120: warning: [deprecation] ProgressDialog in android.app has been deprecated
>   private ProgressDialog coreprog;
>           ^
> /home/Dex-Editor/Dex-Editor/app/src/main/java/modder/hub/dexeditor/DexEditorActivity.java:176: warning: [deprecation] ProgressDialog in android.app has been deprecated
>             prog = new ProgressDialog(DexEditorActivity.this);
>                        ^
> /home/Dex-Editor/Dex-Editor/app/src/main/java/modder/hub/dexeditor/DexEditorActivity.java:176: warning: [deprecation] ProgressDialog(Context) in ProgressDialog has been deprecated
>             prog = new ProgressDialog(DexEditorActivity.this);
>                    ^
> /home/Dex-Editor/Dex-Editor/app/src/main/java/modder/hub/dexeditor/DexEditorActivity.java:205: warning: [deprecation] setMessage(CharSequence) in ProgressDialog has been deprecated
>                             prog.setMessage(classListItem);
>                                 ^
> /home/Dex-Editor/Dex-Editor/app/src/main/java/modder/hub/dexeditor/DexEditorActivity.java:310: warning: [deprecation] onBackPressed() in ComponentActivity has been deprecated
>   public void onBackPressed() {
>               ^
> /home/Dex-Editor/Dex-Editor/app/src/main/java/modder/hub/dexeditor/DexEditorActivity.java:325: warning: [deprecation] Handler() in Handler has been deprecated
>                     new Handler() {
>                     ^
> /home/Dex-Editor/Dex-Editor/app/src/main/java/modder/hub/dexeditor/DexEditorActivity.java:325: warning: [deprecation] Handler() in Handler has been deprecated
>                     new Handler() {
>                                   ^
> /home/Dex-Editor/Dex-Editor/app/src/main/java/modder/hub/dexeditor/DexEditorActivity.java:472: warning: [deprecation] ProgressDialog in android.app has been deprecated
>         coreprog = new ProgressDialog(this);
>                        ^
> /home/Dex-Editor/Dex-Editor/app/src/main/java/modder/hub/dexeditor/DexEditorActivity.java:472: warning: [deprecation] ProgressDialog(Context) in ProgressDialog has been deprecated
>         coreprog = new ProgressDialog(this);
>                    ^
> /home/Dex-Editor/Dex-Editor/app/src/main/java/modder/hub/dexeditor/DexEditorActivity.java:478: warning: [deprecation] setMessage(CharSequence) in ProgressDialog has been deprecated
>       coreprog.setMessage(null);
>               ^
> /home/Dex-Editor/Dex-Editor/app/src/main/java/modder/hub/dexeditor/ImageViewerActivity.java:166: warning: [deprecation] onBackPressed() in ComponentActivity has been deprecated
>   public void onBackPressed() {
>               ^
> /home/Dex-Editor/Dex-Editor/app/src/main/java/modder/hub/dexeditor/MainActivity.java:136: warning: [deprecation] onBackPressed() in ComponentActivity has been deprecated
>             onBackPressed();
>             ^
> /home/Dex-Editor/Dex-Editor/app/src/main/java/com/android/tools/smali/util/jcommander/HelpFormatter.java:168: error: incompatible types: MainParameter cannot be converted to ParameterDescription
>         String[] argumentNames = ExtendedCommands.parameterArgumentNames(leafJc.getMainParameter());
>                                                                                                 ^
> /home/Dex-Editor/Dex-Editor/app/src/main/java/com/android/tools/smali/util/jcommander/HelpFormatter.java:247: error: incompatible types: MainParameter cannot be converted to ParameterDescription
>               ExtendedCommands.parameterArgumentNames(leafJc.getMainParameter());
>                                                                              ^
> /home/Dex-Editor/Dex-Editor/app/src/main/java/com/android/tools/smali/util/jcommander/HelpFormatter.java:299: error: cannot find symbol
>             String commandDesc = leafJc.getCommandDescription(commandName);
>                                        ^
>   symbol:   method getCommandDescription(String)
>   location: variable leafJc of type JCommander
> Note: Some input files use unchecked or unsafe operations.
> 
> > Task :app:compileDebugJavaWithJavac FAILED
> 
> Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.
> 
> You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
> 
> For more on this, please refer to https://docs.gradle.org/8.8/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
> 19 actionable tasks: 19 executed
> 4 errors
> 59 warnings
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':app:compileDebugJavaWithJavac'.
> > Compilation failed; see the compiler error output for details.
> 
> * Try:
> > Run with --info option to get more log output.
> > Run with --scan to get full insights.
> 
> BUILD FAILED
> ```

I don't think this is linked with project compilation failed..may be build tool have issues like you are using JDK while I was building with ecj
